version: '3'
volumes:
  redis_data:
  postgres_data:
services:
  redis:
    image: redis:6
    volumes:
      - redis_data:/data
    ports:
      - 6479:6379
  postgres:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5532:5432
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=message_bus_test
